---
title: "Fitness shifts accompany amino acid changes"
author: "Andrew Nguyen"
date: "2016-February-27"
output: pdf_document
---
#Questions/Objectives
#Hypotheses

#load libraries first
```{r libraries}
library(ggplot2)
library(tidyr)
library(rpart)
library(rpart.plot)
```

#loading in file and changing to long format
##PYR drug
```{r read in file and change to long format}
#read in pyr file
pyr_abs<-read.csv("../Data/20160227_pyr_aa_shifts_drug_abs.csv")
#pyr_abs<-read.csv("20160227_aa_shifts_drug.csv") old but keeping
pyr_relative<-read.csv("../Data/20160227_pyr_aa_shifts_drug_scaled_fitness.csv")
#change alleles to factors
pyr_abs$starting_allele<-as.factor(as.character(pyr_abs$starting_allele))
pyr_abs$end_allele<-as.factor(pyr_abs$end_allele)

#change to long format
mal_long <- gather(pyr_abs, condition, measurement, drug1:drug10)
mal_long2<- gather(pyr_relative, condition, measurement, drug1:drug10)
mal_long$drug<-c(rep(1,32),rep(2,32),rep(3,32),rep(4,32),rep(5,32),rep(6,32),rep(7,32),rep(8,32),rep(9,32),rep(10,32))
mal_long$pyr_relative_measure<-mal_long2$measurement
names(mal_long)[6]<-"pyr_abs"
#write.csv(mal_long,"20160227_pyr_aa_shifts_abs_relative.csv")
#cyc
#read in cyc files
#absolute
cyc2<-read.csv("../Data/20160227_cyc_drug_dose_aa_shifts_abs.csv")
#relative
cyc1<-read.csv("../Data/20160227_cyc_drug_dose_aa_shifts.csv")
cyc_long <- gather(cyc2, condition, measurement, drug1:drug10)
cyc_long2<- gather(cyc1, condition, measurement, drug1:drug10)

mal_long$cyc_abs<-cyc_long2$measurement
mal_long$cyc_relative<-cyc_long$measurement
write.csv(mal_long,"20160227_final_dataset_malaria_pyr_cyc_abs_relative.csv")
```


#sessionInfo
```{r sessioninfo}
sessionInfo()
```

